[package]
name = "client"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "client"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
bevy_math = { workspace = true }
bincode = { workspace = true }
flume = { workspace = true }
json5 = { workspace = true }
rand = { workspace = true }
web-time = { workspace = true }
redb = { workspace = true }

serde_json = "1.0.140"

futures-util = "0.3.31"
bevy = { version = "0.16.0", features = ["web", "jpeg"] }
bevy_simple_text_input = { version = "0.11.0" }
bevy_egui = { version = "0.34.1" }

db = { path = "../db" }
game_common = { path = "../game_common" }
similar = "2.7.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { workspace = true, features = ["full"] }
tokio-tungstenite = { version = "0.26.1", features = ["handshake", "native-tls"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
gloo-timers = { version = "0.3.0", features = ["futures"] }
getrandom = { version = "0.3.3", features = ["wasm_js"] }
ws_stream_wasm = "0.7.4"
wasm-bindgen = "0.2.100"
wasm-bindgen-futures = "0.4.50"
bevy_web_asset = "0.11.0"
web-sys = "0.3.77"
js-sys = "0.3.77"
