[package]
name = "keind"
version = "0.1.0"
edition = "2024"

[lib]

[features]
default = ["web-time"]
zk = []

[dependencies]
anyhow = { workspace = true }
bincode = { workspace = true }
blake3 = { workspace = true }
bevy_math = { workspace = true }
serde = { workspace = true }
json5 = { workspace = true }
rand = { workspace = true }
rand_xoshiro = { workspace = true }
once_cell = { workspace = true }
web-time = { workspace = true, optional = true }
strum = { workspace = true }
flume = { workspace = true }

serde_json = "1.0.140"

