[package]
name = "game-test"
version = "0.1.0"
edition = "2021"

[features]
server = []

[lib]
name = "game_test"
path = "src/lib.rs"

[[bin]]
name = "client"
path = "src/client/main.rs"

[[bin]]
name = "server"
path = "src/server/main.rs"
#required-features = ["server"]

[dependencies]
anyhow = "1.0.95"
bincode = "1.3.3"
futures-util = "0.3.31"
json5 = "0.4.1"
macroquad = { version = "0.4.13", features = ["glam-serde"] }
nanoid = "0.4.0"
once_cell = "1.20.3"
rand = "0.9.0"
serde = { version = "1.0.217", features = ["derive"] }
sled = "0.34.7"
tokio = { version = "1.43.0", features = ["full"] }
tokio-tungstenite = "0.26.1"
tungstenite = "0.26.1"
walkdir = "2.5.0"
websocket = "0.27.1"
