[package]
name = "game-test"
version = "0.1.0"
edition = "2021"

[lib]
name = "game_test"
path = "src/lib.rs"

[[bin]]
name = "client"
path = "src/client/main.rs"

[[bin]]
name = "server"
path = "src/server/main.rs"

[dependencies]
anyhow = "1.0.95"
json5 = "0.4.1"
macroquad = "0.4.13"
once_cell = "1.20.3"
serde = { version = "1.0.217", features = ["derive"] }
tokio = { version = "1.43.0", features = ["full"] }
toml = "0.8.20"
tungstenite = "0.26.1"
websocket = "0.27.1"
