[package]
name = "game_common"
version = "0.1.0"
edition = "2024"

[lib]

[features]
client = ["bevy"]

[build-dependencies]
anyhow = { workspace = true }
json5 = { workspace = true }

serde_json = "1.0.140"

[dependencies]
anyhow = { workspace = true }
bincode = { workspace = true }
blake3 = { workspace = true }
bevy_math = { workspace = true }
serde = { workspace = true }
json5 = { workspace = true }
rand = { workspace = true }
once_cell = { workspace = true }
web-time = { workspace = true }
rand_chacha = { workspace = true }
strum = { workspace = true }
flume = { workspace = true }

bevy = { version = "0.16.0", optional = true }
serde_json = "1.0.140"

db = { path = "../db" }
