[package]
name = "zk-sp1"
version = "0.1.0"
edition = "2024"

[features]
prove = ["sp1-sdk"]

[[bin]]
name = "prove"
required-features = ["prove"]

[dependencies]
sp1-zkvm = "4.0.0"
sp1-sdk = { version = "4.0.0", optional = true }

bevy_math = { workspace = true }

game_common = { path = "../game_common" }
