[package]
name = "server"
version = "0.1.0"
edition = "2024"
license-file = "LICENSE"

[features]
#trace = ["bevy/trace", "bevy/trace_tracy", "tracy-client"]

[[bin]]
name = "server"

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
bevy_math = { workspace = true }
bincode = { workspace = true }
flume = { workspace = true }
json5 = { workspace = true }
nanoid = { workspace = true }
rand = { workspace = true }
web-time = { workspace = true }
tokio = { workspace = true, features = ["full"] }

once_cell = "1.20.3"
futures-util = "0.3.31"
dashmap = "6.1.0"
redb = { version = "2.6.0" }

#tracy-client = { version = "=0.18.0", optional = true }
#rand_chacha = "0.9.0"
#blake3 = { version = "1.8.2", features = ["serde"] }
tokio-tungstenite = { version = "0.26.1", features = ["handshake", "native-tls"] }

db = { path = "../db", features = ["server"] }
game_common = { path = "../game_common" }
engine = { path = "../engine" }
