[package]
name = "engine"
version = "0.1.0"
edition = "2024"

[lib]

[dependencies]
anyhow = { workspace = true }
bevy_math = { workspace = true }
bincode = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
web-time = { workspace = true }
rand_chacha = { workspace = true }
blake3 = { workspace = true }
strum = { workspace = true }
flume = { workspace = true }
once_cell = { workspace = true }

#tracy-client = { version = "=0.18.0", optional = true }

db = { path = "../db" }
