[package]
name = "engine"
version = "0.1.0"
edition = "2024"

[lib]

[features]
default = ["server"]
server = []

[dependencies]
db = { path = "../db" }

anyhow = { workspace = true }
bevy_math = { workspace = true }
bincode = { workspace = true }
json5 = { workspace = true }
nanoid = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
web-time = { workspace = true }
rand_chacha = { workspace = true }
blake3 = { workspace = true }
strum = { workspace = true }
flume = { workspace = true }

once_cell = "1.20.3"

#tracy-client = { version = "=0.18.0", optional = true }
