[package]
name = "db"
version = "0.1.0"
edition = "2024"

[lib]

[features]
default = []

[dependencies]
anyhow = { workspace = true }
bincode = { workspace = true }
nanoid = { workspace = true }
serde = { workspace = true }
strum = { workspace = true }
redb = { workspace = true }
