[package]
name = "db"
version = "0.1.0"
edition = "2024"

[lib]

[features]
default = []
server = ["redb"]

[dependencies]
anyhow = { workspace = true }
bincode = { workspace = true }
nanoid = { workspace = true }
serde = { workspace = true }
blake3 = { workspace = true }
strum = { workspace = true }

redb = { version = "2.6.0", optional = true }
