name: Build ZK proof

on:
  push:
    branches: [main, ci]
    tags: ["playtest*"]
  pull_request:
    branches: [main]

permissions:
  contents: write
  actions: read

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Execute ZKProgram on ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # Linux
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest

          # macOS (ARM64 for new runners)
          - target: aarch64-apple-darwin
            os: macos-latest

          # macOS (Intel x86_64)
          - target: x86_64-apple-darwin
            os: macos-latest

          # Windows
          - target: x86_64-pc-windows-msvc
            os: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y pkg-config libssl-dev libasound2-dev libudev-dev libwayland-dev

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Add target (if cross-compiling)
        run: rustup target add ${{ matrix.target }}

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          # these keys are content checksummed, you can copy and paste it between steps
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo build
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Run noop ZKPrograms
        run: cd packages/keind_zk && cargo run --bin=exec_noop --release

